# Test-only translation units rename real hook implementations before including
# their original source. Calls within that file still reach the real function,
# just as with GNU --wrap; calls from other files reach the harness replacement.
function(stars_test_variant target original)
    set(hook_InitInstance init.c)
    set(hook_ScannerWndProc scan.c)
    set(hook_CchGetString utilgen.c)
    set(hook_Random utilgen.c)
    set(hook_PctPlanetCapacity planet.c)
    set(hook_AlertSz utilgen.c)
    set(hook_WriteRt save.c)
    set(hook_ReadRt file.c)
    set(hook_FCreateFile save.c)
    set(hook_StreamOpen file.c)
    set(hook_StreamClose file.c)
    set(hook_DirtyGame log.c)
    get_target_property(sources ${original} SOURCES)
    set(test_sources)
    foreach(source IN LISTS sources)
        set(defines "")
        foreach(hook IN LISTS ARGN)
            if(NOT DEFINED hook_${hook})
                message(FATAL_ERROR "Unknown test hook: ${hook}")
            endif()
            if(source STREQUAL hook_${hook})
                string(APPEND defines "#define ${hook} __real_${hook}\n")
            endif()
        endforeach()
        if(defines)
            set(wrapper "${CMAKE_CURRENT_BINARY_DIR}/test-hooks/${target}/${source}")
            file(GENERATE OUTPUT "${wrapper}" CONTENT
                "/* STARS_TEST: portable cross-file hook replacement. */\n${defines}#include \"${CMAKE_CURRENT_SOURCE_DIR}/${source}\"\n")
            list(APPEND test_sources "${wrapper}")
        else()
            list(APPEND test_sources "${source}")
        endif()
    endforeach()
    add_library(${target} OBJECT ${test_sources})
    get_target_property(libraries ${original} LINK_LIBRARIES)
    target_link_libraries(${target} PUBLIC ${libraries})
    add_dependencies(${target} stars_version)
endfunction()

function(stars_test_hooks target)
    foreach(hook IN LISTS ARGN)
        target_compile_definitions(${target} PRIVATE __wrap_${hook}=${hook})
    endforeach()
endfunction()
